//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fullPath must start with the masterFolder and indexFolder.
        /// </summary>
        internal static string BackupFile_GetRelativePath_The_fullPath_must_start_with_the_masterFolder_and_indexFolder {
            get {
                return ResourceManager.GetString("BackupFile_GetRelativePath_The_fullPath_must_start_with_the_masterFolder_and_inde" +
                        "xFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash code cannot be null.
        /// </summary>
        internal static string BackupFile_UpdateContentsHash_Hash_code_cannot_be_null {
            get {
                return ResourceManager.GetString("BackupFile_UpdateContentsHash_Hash_code_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero byte Hashcode.
        /// </summary>
        internal static string BackupFile_UpdateContentsHash_Zero_byte_Hashcode {
            get {
                return ResourceManager.GetString("BackupFile_UpdateContentsHash_Zero_byte_Hashcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Admin.
        /// </summary>
        internal static string Main_AdminTitle {
            get {
                return ResourceManager.GetString("Main_AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete any extra files on the backup disk not in our list?.
        /// </summary>
        internal static string Main_AreYouSureDelete {
            get {
                return ResourceManager.GetString("Main_AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect correct backup disk.
        /// </summary>
        internal static string Main_BackupDiskConnectCorrectDisk {
            get {
                return ResourceManager.GetString("Main_BackupDiskConnectCorrectDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect backup disk {0} so we can continue restoring files. Have you connected this disk now?.
        /// </summary>
        internal static string Main_BackupDiskConnectCorrectDisk2 {
            get {
                return ResourceManager.GetString("Main_BackupDiskConnectCorrectDisk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking the connected backup disk.
        /// </summary>
        internal static string Main_BackupDiskError {
            get {
                return ResourceManager.GetString("Main_BackupDiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup disk.
        /// </summary>
        internal static string Main_BackupDiskTitle {
            get {
                return ResourceManager.GetString("Main_BackupDiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling ....
        /// </summary>
        internal static string Main_Cancelling {
            get {
                return ResourceManager.GetString("Main_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete extra files.
        /// </summary>
        internal static string Main_DeleteExtraTitle {
            get {
                return ResourceManager.GetString("Main_DeleteExtraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred during application start. {0}.
        /// </summary>
        internal static string Main_ExceptionOccured {
            get {
                return ResourceManager.GetString("Main_ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are folders to scan queued. Would you like to scan them before closing?.
        /// </summary>
        internal static string Main_FoldersQueued {
            get {
                return ResourceManager.GetString("Main_FoldersQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recalculate the hash codes from the master files?.
        /// </summary>
        internal static string Main_RecalculateAllHashes {
            get {
                return ResourceManager.GetString("Main_RecalculateAllHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate hash codes.
        /// </summary>
        internal static string Main_RecalculateAllHashesTitle {
            get {
                return ResourceManager.GetString("Main_RecalculateAllHashesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check all the symbolic links?.
        /// </summary>
        internal static string Main_RecreateAllMkLinksAre_you_sure {
            get {
                return ResourceManager.GetString("Main_RecreateAllMkLinksAre_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to copy files from multiple backup disks to the new master folder location?.
        /// </summary>
        internal static string Main_RestoreFiles {
            get {
                return ResourceManager.GetString("Main_RestoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a master folder that you&apos;d files the files from backup copied to. This is typically a new drive that will replace the failing drive.
        /// </summary>
        internal static string Main_RestoreFilesMasterFolderToRestoreTo {
            get {
                return ResourceManager.GetString("Main_RestoreFilesMasterFolderToRestoreTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a master folder that you&apos;d files the files from backup disks restored for. This is typically the drive that is now failing.
        /// </summary>
        internal static string Main_RestoreFilesSelectAMasterFolder {
            get {
                return ResourceManager.GetString("Main_RestoreFilesSelectAMasterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup files.
        /// </summary>
        internal static string Main_RestoreFilesTitle {
            get {
                return ResourceManager.GetString("Main_RestoreFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan folders.
        /// </summary>
        internal static string Main_ScanFoldersTitle {
            get {
                return ResourceManager.GetString("Main_ScanFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watchers = OFF.
        /// </summary>
        internal static string Main_SetupFileWatchers_Off {
            get {
                return ResourceManager.GetString("Main_SetupFileWatchers_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watchers = ON.
        /// </summary>
        internal static string Main_SetupFileWatchers_On {
            get {
                return ResourceManager.GetString("Main_SetupFileWatchers_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Links.
        /// </summary>
        internal static string Main_SymbolicLinksTitle {
            get {
                return ResourceManager.GetString("Main_SymbolicLinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred. Cancelling operation. {0}.
        /// </summary>
        internal static string Main_TaskWrapperException {
            get {
                return ResourceManager.GetString("Main_TaskWrapperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to rebuild the master list?.
        /// </summary>
        internal static string Main_UpdateMasterFiles {
            get {
                return ResourceManager.GetString("Main_UpdateMasterFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild master list.
        /// </summary>
        internal static string Main_UpdateMasterFilesTitle {
            get {
                return ResourceManager.GetString("Main_UpdateMasterFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate rule number detected in rules.xml.
        /// </summary>
        internal static string Rules_Load_Duplicate_rule_number_detected_in_rules_xml {
            get {
                return ResourceManager.GetString("Rules_Load_Duplicate_rule_number_detected_in_rules_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file rules.
        /// </summary>
        internal static string Rules_Load_Missing_file_rules {
            get {
                return ResourceManager.GetString("Rules_Load_Missing_file_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is a null reference or an empty string.
        /// </summary>
        internal static string Utils_DirectoryNameNullOrEmpty {
            get {
                return ResourceManager.GetString("Utils_DirectoryNameNullOrEmpty", resourceCulture);
            }
        }
    }
}
