//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash code cannot be null.
        /// </summary>
        internal static string BackupFile_HashCodeNotNull {
            get {
                return ResourceManager.GetString("BackupFile_HashCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fullPath must start with the masterFolder and indexFolder.
        /// </summary>
        internal static string BackupFile_The_fullPathNotCorrect {
            get {
                return ResourceManager.GetString("BackupFile_The_fullPathNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMM-yy.
        /// </summary>
        internal static string DateTime_ddMMMyy {
            get {
                return ResourceManager.GetString("DateTime_ddMMMyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string DateTime_HHmm {
            get {
                return ResourceManager.GetString("DateTime_HHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h&apos;h &apos;mm&apos;m&apos;.
        /// </summary>
        internal static string DateTime_TimeFormat {
            get {
                return ResourceManager.GetString("DateTime_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateTime_yyyyMMdd {
            get {
                return ResourceManager.GetString("DateTime_yyyyMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is empty. Not supported.
        /// </summary>
        internal static string DirectoryEmpty {
            get {
                return ResourceManager.GetString("DirectoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is a null reference or an empty string.
        /// </summary>
        internal static string DirectoryNameNullOrEmpty {
            get {
                return ResourceManager.GetString("DirectoryNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} not found.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 file with same ContentsHashcode {0}.
        /// </summary>
        internal static string DuplicateContentsHashCode {
            get {
                return ResourceManager.GetString("DuplicateContentsHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate hash found on load of {0}.
        /// </summary>
        internal static string DuplicateHashCode {
            get {
                return ResourceManager.GetString("DuplicateHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory name {0} is invalid.
        /// </summary>
        internal static string InvalidDirName {
            get {
                return ResourceManager.GetString("InvalidDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory name &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string InvalidDirNameNotExists {
            get {
                return ResourceManager.GetString("InvalidDirNameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos;({1}) is invalid for Enum type &apos;{2}&apos;.
        /// </summary>
        internal static string InvalidEnumArgument {
            get {
                return ResourceManager.GetString("InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Admin.
        /// </summary>
        internal static string Main_AdminTitle {
            get {
                return ResourceManager.GetString("Main_AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete any extra files on the backup disk not in our list?.
        /// </summary>
        internal static string Main_AreYouSureDelete {
            get {
                return ResourceManager.GetString("Main_AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking the connected backup disk.
        /// </summary>
        internal static string Main_BackupDiskError {
            get {
                return ResourceManager.GetString("Main_BackupDiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup disk.
        /// </summary>
        internal static string Main_BackupDiskTitle {
            get {
                return ResourceManager.GetString("Main_BackupDiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Main_Cancelling {
            get {
                return ResourceManager.GetString("Main_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0}.
        /// </summary>
        internal static string Main_Checking {
            get {
                return ResourceManager.GetString("Main_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string Main_Completed {
            get {
                return ResourceManager.GetString("Main_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}.
        /// </summary>
        internal static string Main_Copying {
            get {
                return ResourceManager.GetString("Main_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect backup disk {0} so we can continue restoring files. Have you connected this disk now?.
        /// </summary>
        internal static string Main_CorrectDiskPrompt {
            get {
                return ResourceManager.GetString("Main_CorrectDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect correct backup disk.
        /// </summary>
        internal static string Main_CorrectDiskTitle {
            get {
                return ResourceManager.GetString("Main_CorrectDiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete extra files.
        /// </summary>
        internal static string Main_DeleteExtraTitle {
            get {
                return ResourceManager.GetString("Main_DeleteExtraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory scan skipped. It will be scanned again in {0}.
        /// </summary>
        internal static string Main_Directory_scan_skipped {
            get {
                return ResourceManager.GetString("Main_Directory_scan_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Estimated finish by .
        /// </summary>
        internal static string Main_Estimated_finish_by_ {
            get {
                return ResourceManager.GetString("Main_Estimated_finish_by_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Estimated finish by tomorrow at .
        /// </summary>
        internal static string Main_Estimated_finish_by_tomorrow_at_ {
            get {
                return ResourceManager.GetString("Main_Estimated_finish_by_tomorrow_at_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred during application start. {0}.
        /// </summary>
        internal static string Main_ExceptionOccured {
            get {
                return ResourceManager.GetString("Main_ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watchers = {0}.
        /// </summary>
        internal static string Main_FileWatchersButton {
            get {
                return ResourceManager.GetString("Main_FileWatchersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are folders to scan queued. Would you like to scan them before closing?.
        /// </summary>
        internal static string Main_FoldersQueued {
            get {
                return ResourceManager.GetString("Main_FoldersQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring = {0}.
        /// </summary>
        internal static string Main_MonitoringButton {
            get {
                return ResourceManager.GetString("Main_MonitoringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Main_OFF {
            get {
                return ResourceManager.GetString("Main_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Main_ON {
            get {
                return ResourceManager.GetString("Main_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the next backup disk now.
        /// </summary>
        internal static string Main_Please_insert_the_next_backup_disk_now {
            get {
                return ResourceManager.GetString("Main_Please_insert_the_next_backup_disk_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recalculate the hash codes from the master files?.
        /// </summary>
        internal static string Main_RecalculateAllHashes {
            get {
                return ResourceManager.GetString("Main_RecalculateAllHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate hash codes.
        /// </summary>
        internal static string Main_RecalculateAllHashesTitle {
            get {
                return ResourceManager.GetString("Main_RecalculateAllHashesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check all the symbolic links?.
        /// </summary>
        internal static string Main_RecreateAllSymbolicLinks {
            get {
                return ResourceManager.GetString("Main_RecreateAllSymbolicLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to copy files from multiple backup disks to the new directory location?.
        /// </summary>
        internal static string Main_RestoreFiles {
            get {
                return ResourceManager.GetString("Main_RestoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a directory that you&apos;d like files from backup copied to. This is typically a new drive that will replace the failing drive.
        /// </summary>
        internal static string Main_RestoreFilesDirectoryToRestoreTo {
            get {
                return ResourceManager.GetString("Main_RestoreFilesDirectoryToRestoreTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a directory that you&apos;d like from backup disks restored for. This is typically the drive that is now failing.
        /// </summary>
        internal static string Main_RestoreFilesSelectDirectory {
            get {
                return ResourceManager.GetString("Main_RestoreFilesSelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup files.
        /// </summary>
        internal static string Main_RestoreFilesTitle {
            get {
                return ResourceManager.GetString("Main_RestoreFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Main_Saved {
            get {
                return ResourceManager.GetString("Main_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Folders failed.
        /// </summary>
        internal static string Main_ScanDirectoriesAsync_Scan_Directories_failed {
            get {
                return ResourceManager.GetString("Main_ScanDirectoriesAsync_Scan_Directories_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting empty folders in {0}.
        /// </summary>
        internal static string Main_ScanFolders_Deleting_empty_folders_in__0_ {
            get {
                return ResourceManager.GetString("Main_ScanFolders_Deleting_empty_folders_in__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan folders.
        /// </summary>
        internal static string Main_ScanFoldersTitle {
            get {
                return ResourceManager.GetString("Main_ScanFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}.
        /// </summary>
        internal static string Main_Scanning {
            get {
                return ResourceManager.GetString("Main_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending = {0}.
        /// </summary>
        internal static string Main_SendingPushoverButton {
            get {
                return ResourceManager.GetString("Main_SendingPushoverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}.
        /// </summary>
        internal static string Main_Skipping {
            get {
                return ResourceManager.GetString("Main_Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Test Disks = {0}.
        /// </summary>
        internal static string Main_SpeedTestDisksButton {
            get {
                return ResourceManager.GetString("Main_SpeedTestDisksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed testing {0}.
        /// </summary>
        internal static string Main_SpeedTesting {
            get {
                return ResourceManager.GetString("Main_SpeedTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Links.
        /// </summary>
        internal static string Main_SymbolicLinksTitle {
            get {
                return ResourceManager.GetString("Main_SymbolicLinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred. Cancelling operation. {0}.
        /// </summary>
        internal static string Main_TaskWrapperException {
            get {
                return ResourceManager.GetString("Main_TaskWrapperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to rebuild the master list?.
        /// </summary>
        internal static string Main_UpdateMasterFiles {
            get {
                return ResourceManager.GetString("Main_UpdateMasterFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild master list.
        /// </summary>
        internal static string Main_UpdateMasterFilesTitle {
            get {
                return ResourceManager.GetString("Main_UpdateMasterFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup = {0}.
        /// </summary>
        internal static string Main_UpdateScheduledBackupButton {
            get {
                return ResourceManager.GetString("Main_UpdateScheduledBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine Directory or Relative Path.
        /// </summary>
        internal static string MediaBackup_UnableToDetermineDirectoryOrRelativePath {
            get {
                return ResourceManager.GetString("MediaBackup_UnableToDetermineDirectoryOrRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate rule number detected in rules.xml.
        /// </summary>
        internal static string Rules_DuplicateRuleNumber {
            get {
                return ResourceManager.GetString("Rules_DuplicateRuleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file rules.
        /// </summary>
        internal static string Rules_MissingFileRules {
            get {
                return ResourceManager.GetString("Rules_MissingFileRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0} {1}.
        /// </summary>
        internal static string UnableToLoadXml {
            get {
                return ResourceManager.GetString("UnableToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid application name.
        /// </summary>
        internal static string Utils_Not_a_valid_application_name {
            get {
                return ResourceManager.GetString("Utils_Not_a_valid_application_name", resourceCulture);
            }
        }
    }
}
