//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Admin.
        /// </summary>
        internal static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files checked in last {0} days.
        /// </summary>
        internal static string AllFilesCheckedInLastNDays {
            get {
                return ResourceManager.GetString("AllFilesCheckedInLastNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupManager is already running.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete any extra files on the backup disk not in our list?.
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a very fast speed.
        /// </summary>
        internal static string AVeryFastSpeed {
            get {
                return ResourceManager.GetString("AVeryFastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup disk.
        /// </summary>
        internal static string BackupDisk {
            get {
                return ResourceManager.GetString("BackupDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking the connected backup disk.
        /// </summary>
        internal static string BackupDiskError {
            get {
                return ResourceManager.GetString("BackupDiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupManager started.
        /// </summary>
        internal static string BackupManagerStarted {
            get {
                return ResourceManager.GetString("BackupManagerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup disks not checked in {0} days - {1}.
        /// </summary>
        internal static string CheckForOldBackupDisks {
            get {
                return ResourceManager.GetString("CheckForOldBackupDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0}.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking broken links {0}%.
        /// </summary>
        internal static string CheckingBrokenLinks {
            get {
                return ResourceManager.GetString("CheckingBrokenLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}
        ///Total: {1}
        ///Free: {2}
        ///Read: {3}
        ///Write: {4}.
        /// </summary>
        internal static string ConnectedDiskInfo {
            get {
                return ResourceManager.GetString("ConnectedDiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] {2} free.
        ///Skipping {3} as not enough free space.
        /// </summary>
        internal static string CopyFileInternalSkipping {
            get {
                return ResourceManager.GetString("CopyFileInternalSkipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}]
        ///Skipping copy of {2} as it exists already..
        /// </summary>
        internal static string CopyFilesFileExists {
            get {
                return ResourceManager.GetString("CopyFilesFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free on backup disk.
        /// </summary>
        internal static string CopyFilesFreeOnBackupDisk {
            get {
                return ResourceManager.GetString("CopyFilesFreeOnBackupDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] {2} free.
        ///Copying {3} at {4}{5}.
        /// </summary>
        internal static string CopyFilesMainMessage {
            get {
                return ResourceManager.GetString("CopyFilesMainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} files still to backup at {1}.
        ///.
        /// </summary>
        internal static string CopyFilesStillToCopy {
            get {
                return ResourceManager.GetString("CopyFilesStillToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} files to backup at {1}.
        /// </summary>
        internal static string CopyFilesToBackup {
            get {
                return ResourceManager.GetString("CopyFilesToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect backup disk {0} so we can continue restoring files. Have you connected this disk now?.
        /// </summary>
        internal static string CorrectDiskPrompt {
            get {
                return ResourceManager.GetString("CorrectDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect correct backup disk.
        /// </summary>
        internal static string CorrectDiskTitle {
            get {
                return ResourceManager.GetString("CorrectDiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new disk.
        /// </summary>
        internal static string CreateNewDisk {
            get {
                return ResourceManager.GetString("CreateNewDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMM-yy.
        /// </summary>
        internal static string DateTime_ddMMMyy {
            get {
                return ResourceManager.GetString("DateTime_ddMMMyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string DateTime_HHmm {
            get {
                return ResourceManager.GetString("DateTime_HHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h&apos;h &apos;mm&apos;m&apos;.
        /// </summary>
        internal static string DateTime_TimeFormat {
            get {
                return ResourceManager.GetString("DateTime_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateTime_yyyyMMdd {
            get {
                return ResourceManager.GetString("DateTime_yyyyMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete extra files.
        /// </summary>
        internal static string DeleteExtraTitle {
            get {
                return ResourceManager.GetString("DeleteExtraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting empty directories in {0}.
        /// </summary>
        internal static string DeletingEmptyDirectories {
            get {
                return ResourceManager.GetString("DeletingEmptyDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are directories to scan queued. Would you like to scan them before closing?.
        /// </summary>
        internal static string DirectoriesQueued {
            get {
                return ResourceManager.GetString("DirectoriesQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is empty. Not supported.
        /// </summary>
        internal static string DirectoryEmpty {
            get {
                return ResourceManager.GetString("DirectoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is a null reference or an empty string.
        /// </summary>
        internal static string DirectoryHasNoValue {
            get {
                return ResourceManager.GetString("DirectoryHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available or writable.
        /// </summary>
        internal static string DirectoryIsNotWritable {
            get {
                return ResourceManager.GetString("DirectoryIsNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} not found.
        /// </summary>
        internal static string DirectoryNotFound1 {
            get {
                return ResourceManager.GetString("DirectoryNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory name &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string DirectoryNotFound2 {
            get {
                return ResourceManager.GetString("DirectoryNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory name {0} is invalid.
        /// </summary>
        internal static string DirectoryNotFound3 {
            get {
                return ResourceManager.GetString("DirectoryNotFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory scan skipped. It will be scanned again in {0}.
        /// </summary>
        internal static string DirectoryScanSkipped {
            get {
                return ResourceManager.GetString("DirectoryScanSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk is not empty. Please empty the disk before preparing for backup..
        /// </summary>
        internal static string DiskNotEmpty {
            get {
                return ResourceManager.GetString("DiskNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk not empty.
        /// </summary>
        internal static string DiskNotEmptyTitle {
            get {
                return ResourceManager.GetString("DiskNotEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 file with same ContentsHashcode {0} at {1} and {2}.
        /// </summary>
        internal static string DuplicateContentsHashCode {
            get {
                return ResourceManager.GetString("DuplicateContentsHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate hash found on load of {0}.
        /// </summary>
        internal static string DuplicateHashCode {
            get {
                return ResourceManager.GetString("DuplicateHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate rule number detected in rules.xml.
        /// </summary>
        internal static string DuplicateRuleNumber {
            get {
                return ResourceManager.GetString("DuplicateRuleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating info for backup disk {0}.
        /// </summary>
        internal static string ErrorUpdatingInfoForBackupDisk {
            get {
                return ResourceManager.GetString("ErrorUpdatingInfoForBackupDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Estimated finish by .
        /// </summary>
        internal static string EstimatedFinishBy {
            get {
                return ResourceManager.GetString("EstimatedFinishBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Estimated finish by tomorrow at .
        /// </summary>
        internal static string EstimatedFinishByTomorrow {
            get {
                return ResourceManager.GetString("EstimatedFinishByTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred during application start. {0}.
        /// </summary>
        internal static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart the service &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToRestartService {
            get {
                return ResourceManager.GetString("FailedToRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the new process &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToStart {
            get {
                return ResourceManager.GetString("FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the new process &apos;{0}&apos; as its not found at {1} (expanded to {2}).
        /// </summary>
        internal static string FailedToStartAsNotFound {
            get {
                return ResourceManager.GetString("FailedToStartAsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop the service &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToStopTheService {
            get {
                return ResourceManager.GetString("FailedToStopTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists already so deleting {0} instead.
        /// </summary>
        internal static string FileExistsAlreadySoDeleting {
            get {
                return ResourceManager.GetString("FileExistsAlreadySoDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOException during copy. Skipping file. Details {0}.
        /// </summary>
        internal static string FileIOExceptionDuringCopy {
            get {
                return ResourceManager.GetString("FileIOExceptionDuringCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked so can&apos;t be processed now.
        /// </summary>
        internal static string FileIsLocked {
            get {
                return ResourceManager.GetString("FileIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not accessible.
        /// </summary>
        internal static string FileIsNotAccessible {
            get {
                return ResourceManager.GetString("FileIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found. It&apos;s most likely been replaced since our scan..
        /// </summary>
        internal static string FileNotFound2 {
            get {
                return ResourceManager.GetString("FileNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename {0} to {1} as it already exists.
        /// </summary>
        internal static string FileRenameFailed {
            get {
                return ResourceManager.GetString("FileRenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rename required for video codec.
        /// </summary>
        internal static string FileRenameRequiredForVideoCodec {
            get {
                return ResourceManager.GetString("FileRenameRequiredForVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The count of files to backup is too low. Check connections to nas drives.
        /// </summary>
        internal static string FilesCountIsTooLow {
            get {
                return ResourceManager.GetString("FilesCountIsTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watchers = {0}.
        /// </summary>
        internal static string FileWatchersButton {
            get {
                return ResourceManager.GetString("FileWatchersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed space inside.
        /// </summary>
        internal static string FixedSpace {
            get {
                return ResourceManager.GetString("FixedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fullPath must start with the masterFolder and indexFolder.
        /// </summary>
        internal static string FullPathNotCorrect {
            get {
                return ResourceManager.GetString("FullPathNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash code cannot be null.
        /// </summary>
        internal static string HashCodeNotNull {
            get {
                return ResourceManager.GetString("HashCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with the hash codes on the source and backup disk. It&apos;s likely the source file has changed since the last backup of {0}. It could be that the source file or destination file are corrupted or in use by another process..
        /// </summary>
        internal static string HashCodesError {
            get {
                return ResourceManager.GetString("HashCodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with the hash codes on the source directory and the backup disk..
        /// </summary>
        internal static string HashCodesError2 {
            get {
                return ResourceManager.GetString("HashCodesError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos;({1}) is invalid for Enum type &apos;{2}&apos;.
        /// </summary>
        internal static string InvalidEnumArgument {
            get {
                return ResourceManager.GetString("InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - not checked in {1} day(s) on disk {2}.
        /// </summary>
        internal static string ListingFileNotCheckedInDaysOnDisk {
            get {
                return ResourceManager.GetString("ListingFileNotCheckedInDaysOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing files not checked in {0} days.
        /// </summary>
        internal static string ListingFilesNotCheckedInDays {
            get {
                return ResourceManager.GetString("ListingFilesNotCheckedInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file rules.
        /// </summary>
        internal static string MissingFileRules {
            get {
                return ResourceManager.GetString("MissingFileRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} version could not be checked..
        /// </summary>
        internal static string MonitorCheckLatestVersionsCouldNotBeChecked {
            get {
                return ResourceManager.GetString("MonitorCheckLatestVersionsCouldNotBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring = {0}.
        /// </summary>
        internal static string MonitoringButton {
            get {
                return ResourceManager.GetString("MonitoringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; started.
        /// </summary>
        internal static string MonitorServicesStarted {
            get {
                return ResourceManager.GetString("MonitorServicesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version of service {0} is available. Version {1} is installed and {2} is available..
        /// </summary>
        internal static string NewerVersionOfApplicationAvailable {
            get {
                return ResourceManager.GetString("NewerVersionOfApplicationAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version of service {0} available so not stopping/starting service. Version {1} is installed and {2} is available..
        /// </summary>
        internal static string NewerVersionOfServiceAvailable {
            get {
                return ResourceManager.GetString("NewerVersionOfServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid application name.
        /// </summary>
        internal static string NotValidApplicationName {
            get {
                return ResourceManager.GetString("NotValidApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a valid backup share.
        /// </summary>
        internal static string NoValidBackupShare {
            get {
                return ResourceManager.GetString("NoValidBackupShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a fixed space so renaming it.
        /// </summary>
        internal static string PathHasAFixedSpace {
            get {
                return ResourceManager.GetString("PathHasAFixedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is longer than 256 characters.
        /// </summary>
        internal static string PathIsLongerThan256Characters {
            get {
                return ResourceManager.GetString("PathIsLongerThan256Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a path longer than 256 characters. Please rename manually..
        /// </summary>
        internal static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the next backup disk now.
        /// </summary>
        internal static string PleaseInsertTheNextBackupDiskNow {
            get {
                return ResourceManager.GetString("PleaseInsertTheNextBackupDiskNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free is very low. Prepare new backup disk.
        /// </summary>
        internal static string PrepareNewBackupDisk {
            get {
                return ResourceManager.GetString("PrepareNewBackupDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to prepare a new backup disk?.
        /// </summary>
        internal static string PrepareNewBackupDiskAreYouSure {
            get {
                return ResourceManager.GetString("PrepareNewBackupDiskAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}%.
        /// </summary>
        internal static string ProcessingPercentage {
            get {
                return ResourceManager.GetString("ProcessingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recalculate the hash codes from the master files?.
        /// </summary>
        internal static string RecalculateAllHashes {
            get {
                return ResourceManager.GetString("RecalculateAllHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate hash codes.
        /// </summary>
        internal static string RecalculateAllHashesTitle {
            get {
                return ResourceManager.GetString("RecalculateAllHashesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check all the symbolic links?.
        /// </summary>
        internal static string RecreateAllSymbolicLinks {
            get {
                return ResourceManager.GetString("RecreateAllSymbolicLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting &apos;{0}&apos;.
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to copy files from multiple backup disks to the new directory location?.
        /// </summary>
        internal static string RestoreFilesAreYouSure {
            get {
                return ResourceManager.GetString("RestoreFilesAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a directory that you&apos;d like files from backup copied to. This is typically a new drive that will replace the failing drive.
        /// </summary>
        internal static string RestoreFilesDirectoryToRestoreTo {
            get {
                return ResourceManager.GetString("RestoreFilesDirectoryToRestoreTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a directory that you&apos;d like from backup disks restored for. This is typically the drive that is now failing.
        /// </summary>
        internal static string RestoreFilesSelectDirectory {
            get {
                return ResourceManager.GetString("RestoreFilesSelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup files.
        /// </summary>
        internal static string RestoreFilesTitle {
            get {
                return ResourceManager.GetString("RestoreFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring files from directory {0}.
        /// </summary>
        internal static string RestoringFilesFromDirectory {
            get {
                return ResourceManager.GetString("RestoringFilesFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring files to target directory {0}.
        /// </summary>
        internal static string RestoringFilesToTargetDirectory {
            get {
                return ResourceManager.GetString("RestoringFilesToTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Directories Failed.
        /// </summary>
        internal static string ScanDirectoriesFailed {
            get {
                return ResourceManager.GetString("ScanDirectoriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan directories.
        /// </summary>
        internal static string ScanFoldersTitle {
            get {
                return ResourceManager.GetString("ScanFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}.
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending = {0}.
        /// </summary>
        internal static string SendingPushoverButton {
            get {
                return ResourceManager.GetString("SendingPushoverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is down. {1} failure{2} in the last {3}..
        /// </summary>
        internal static string ServiceIsDown {
            get {
                return ResourceManager.GetString("ServiceIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}.
        /// </summary>
        internal static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Test Disks = {0}.
        /// </summary>
        internal static string SpeedTestDisksButton {
            get {
                return ResourceManager.GetString("SpeedTestDisksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed testing {0}.
        /// </summary>
        internal static string SpeedTesting {
            get {
                return ResourceManager.GetString("SpeedTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}.
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping all &apos;{0}&apos; processes that match.
        /// </summary>
        internal static string StoppingAllProcessesThatMatch {
            get {
                return ResourceManager.GetString("StoppingAllProcessesThatMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Links.
        /// </summary>
        internal static string SymbolicLinksTitle {
            get {
                return ResourceManager.GetString("SymbolicLinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred. Cancelling operation. {0}.
        /// </summary>
        internal static string TaskWrapperException {
            get {
                return ResourceManager.GetString("TaskWrapperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine Directory or Relative Path.
        /// </summary>
        internal static string UnableToDetermineDirectoryOrRelativePath {
            get {
                return ResourceManager.GetString("UnableToDetermineDirectoryOrRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load ffprobe.exe for {0}.
        /// </summary>
        internal static string UnableToLoadFFProbe {
            get {
                return ResourceManager.GetString("UnableToLoadFFProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0} {1}.
        /// </summary>
        internal static string UnableToLoadXml {
            get {
                return ResourceManager.GetString("UnableToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to scan all the directories?.
        /// </summary>
        internal static string UpdateMasterFiles {
            get {
                return ResourceManager.GetString("UpdateMasterFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild master list.
        /// </summary>
        internal static string UpdateMasterFilesTitle {
            get {
                return ResourceManager.GetString("UpdateMasterFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} day{1} ago.
        /// </summary>
        internal static string UpdateOldestBackupDiskNDaysAgo {
            get {
                return ResourceManager.GetString("UpdateOldestBackupDiskNDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup = {0}.
        /// </summary>
        internal static string UpdateScheduledBackupButton {
            get {
                return ResourceManager.GetString("UpdateScheduledBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}%.
        /// </summary>
        internal static string UpdatingPercentage {
            get {
                return ResourceManager.GetString("UpdatingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Checking = {0}.
        /// </summary>
        internal static string VersionCheckingButton {
            get {
                return ResourceManager.GetString("VersionCheckingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] VideoCodec correct for {2}.
        /// </summary>
        internal static string VideoCodecCorrect {
            get {
                return ResourceManager.GetString("VideoCodecCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] VideoCodec to change for {2}. Was {3} and should be {4}.
        /// </summary>
        internal static string VideoCodecNotCorrect {
            get {
                return ResourceManager.GetString("VideoCodecNotCorrect", resourceCulture);
            }
        }
    }
}
